const products = [

    {
        title: 'Car Amplifier',
        slug: 'Car-amplifier',
        parent: 'Audio',
        children: 'Audio Parts',
        image:
            'https://res.cloudinary.com/dfa6tp3ps/image/upload/v1670345138/sor%20service/audio/amplifiers_ic_5_zig57k.jpg',
        originalPrice: 800,
        price: 800,
        discount: 0,
        quantity: 100,
        active: false,
        type: 'Car Sound',
        tag: JSON.stringify(['audio', 'audio parts']),
        description:
            ' Boosts the low-level audio signal generated by the head unit so that its powerful enough to move the cones of the speakers in the system and create sound.',
    },

    {
        title: 'Vehicle Battery',
        slug: 'vehicle-battery',
        parent: 'Battery',
        children: 'Battery Parts',
        image: 'https://res.cloudinary.com/dfa6tp3ps/image/upload/v1670345109/sor%20service/battery/batteries-components_ic_5_lnyw4i.jpg',
        originalPrice: 2000,
        price: 2000,
        discount: 0,
        quantity: 100,
        active: true,
        type: 'Vehicle Battery',
        tag: JSON.stringify(['Battery', 'battery parts']),
        description:
            'An automotive battery or car battery is a rechargeable battery that is used to start a motor vehicle. Its main purpose is to provide an electric current to',
    },

    {
        title: 'Vehicle Covers',
        slug: 'vehicle-covers',
        parent: 'Exterior',
        children: 'Car Covers',
        image: 'https://res.cloudinary.com/dfa6tp3ps/image/upload/v1670345133/sor%20service/exterior/car-covers_ic_5_enjzfv.jpg',
        originalPrice: 1200,
        price: 1200,
        discount: 0,
        quantity: 50,
        active: true,
        type: 'Vehicle Covers',
        tag: JSON.stringify(['Covers', 'car Covers']),
        description:
            'A product that can be used to cover a car, possibly protecting it against the elements. It is often used when a vehicle',
    },

    {
        title: 'Floor Mats',
        slug: 'floor-mats',
        parent: 'Interior',
        children: 'Car Mats',
        image: 'https://res.cloudinary.com/dfa6tp3ps/image/upload/v1670345104/sor%20service/interior/custom-floor-mats_ic_5_dvgbpk.jpg',
        originalPrice: 1200,
        price: 1200,
        discount: 0,
        quantity: 50,
        active: true,
        type: 'Vehicle Covers',
        tag: JSON.stringify(['Mats', 'car mats']),
        description:
            'A product that can be used to cover a car, possibly protecting it against the elements. It is often used when a vehicle',
    },
]

module.exports = products;

